#%RAML 1.0 DataType
properties:
  Bundesland:
    type: string
    example: "Baden-Württemberg"
  Stadt:
    type: string
    example: "Karlsruhe"
  Name:
    type: string
    example: "Vereinsname"
  Webseite:
    type: string
    example: "https://verein.karlsruhe.de/"
