steps:
  # Build the Go binary.
  - name: 'gcr.io/cloud-builders/go:alpine-1.23'
    args: ['mod', 'download']
    env: ['GOPATH=/go']
  # Run the tests.
  - name: 'gcr.io/cloud-builders/go:alpine-1.23'
    args: ['test', './...', ' -p', '8']
    env: ['GOPATH=/go']
  - name: 'gcr.io/cloud-builders/go:alpine-1.23'
    args: ['build', '-v', '-o', '/app/bin/endpoint1', './src/cmd/endpoint1']
    env: ['GOPATH=/go']
  # Build the production image.
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '--tag=gcr.io/$PROJECT_ID/endpoint1',
      '--file=Dockerfile-cloudbuild',
      '.'
    ]
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/endpoint1' ]
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'endpoint1', '--image', 'gcr.io/$PROJECT_ID/endpoint1', '--region', 'europe-west4',
           '--cpu=1', '--max-instances=2', '--memory=128Mi', '--timeout=20s', '--no-allow-unauthenticated', '--concurrency=80']
images:
  - 'gcr.io/$PROJECT_ID/endpoint1'
options:
  logging: CLOUD_LOGGING_ONLY
  volumes:
    - name: go-modules
      path: /go