#%RAML 1.0 DataType
description: A request to get a Minecraft user account whitelisted.
properties:
  username:
    type: string
    required: true
    example: "Herobrine"
  secret:
    type: string
    required: true
    example: "please-let-me-play-on-this-server"