#%RAML 1.0 DataType
description: A request to change the user's mail password.
properties:
  email:
    type: string
    required: true
    example: "user@example.com"
  oldpassword:
    type: string
    required: true
    example: "hunter2"
  newpassword:
    type: string
    required: true
    example: "123456"