#%RAML 1.0 DataType
properties:
  title?:
    type: string
    example: Hey there
  text?:
    type: string
    example: I have something to say here...
  author?:
    type: string
    example: user/123
  created?:
    description: RFC 3339 date
    type: string