#%RAML 1.0 DataType
properties:
  title?:
    type: string
    example: My Item
  text?:
    type: string
    example: Something to describe
  translated?:
    description: whether this has automatically been translated from another language
    type: boolean
    example: false