#%RAML 1.0 DataType
properties:
  _id?:
    type: string
    description: key to retrieve an entity
    examples:
      user: user/4711
      location: location/1337
      training: training/420
      page: page/69