#%RAML 1.0 DataType
properties:
  lat?:
    description: Latitude
    example: 53.551086
    type: number
  lng?:
    description: Longitude
    example: 9.993682
    type: number
  include?:
    description: 'comma-separated list of sections to include. Choose from: photos,comments,descriptions'
    example: photos,descriptions
    type: string
  skip?:
    description: skip over this many results
    type: integer
  limit?:
    description: show only this many results
    type: integer
