#%RAML 1.0 DataType
properties:
  key?:
    type: string
    example: "123"
  created?:
    description: RFC 3339 date
    type: string
  modified?:
    description: RFC 3339 date
    type: string
  provider?:
    type: string
    example: facebook
  subject?:
    type: string
    example: "10150000000001234"
  enabled?:
    type: boolean
    example: true