#%RAML 1.0 DataType
properties:
  _id?:
    type: string
    description: key to retrieve an entity
    example: page/123
  information?:
    description: Extra information as string map
    properties:
      /.*/: string
  descriptions?: Descriptions
  photos?: Photo[]
  comments?: Comment[]