#%RAML 1.0 DataType
properties:
  src?:
    type: string
    example: image.jpg
  w?:
    type: integer
    example: 640
  h?:
    type: integer
    example: 480
  lat?:
    type: number
    description: The latitude coordinate of the uploaded image
    example: 54.3243827819444
  lon?:
    type: number
    description: The longitude coordinate of the uploaded image
    example: 10.1457242963889
  c?:
    type: string
    description: The color information of the uploaded image
    example: itV8NsR8q8ibacicQzREZmd3ZUZVmING