#%RAML 1.0 DataType
properties:
  training?: Training
  location?: Location
  locationKey?:
    type: string
    description: key to retrieve an entity
    example: "123"
  organiserKeys?: string[]
  organisers?: User[]