#%RAML 1.0 DataType
properties:
  weekday?:
    description: Day of the week (1-7) or 0 to ignore
    example: 0
    type: integer
    minimum: 0
    maximum: 7
  key?:
    description: User key
    example: john.doe_123
    type: string
  name?:
    description: User name
    example: John Doe
    type: string
  type?:
    description: User type
    example: athlete
    type: string
  text?:
    description: Text to search for
    example: backflip
    type: string
  language?:
    description: Language of the text to search for
    example: en
  include?:
    description: 'comma-separated list of sections to include. Choose from: photos,comments'
    example: photos,comments
    type: string
  skip?:
    description: skip over this many results
    type: integer
  limit?:
    description: show only this many results
    type: integer
